import { useEffect, useState } from 'react'
import { useTranscript } from './hooks/useTranscript'
import { UrlInput } from './components/UrlInput'
import { TranscriptView } from './components/TranscriptView'
import { Skeleton } from './components/Skeleton'
import { FeaturePanel, type Feature } from './components/FeaturePanel'
import {
  BrainIcon,
  CheckIcon,
  ClockIcon,
  FileTextIcon,
  LinkIcon,
  ShieldIcon,
  YoutubeIcon,
} from './components/icons'

const FEATURES: Feature[] = [
  {
    id: 'local-ai',
    label: 'Local AI',
    icon: BrainIcon,
    headline: 'Summaries run on your local model.',
    points: [
      'Your data never leaves your computer',
      'Works with Ollama and custom local models',
      'No cloud account or API key required',
    ],
  },
  {
    id: 'privacy-first',
    label: 'Privacy First',
    icon: ShieldIcon,
    headline: 'Only the transcript is fetched from YouTube.',
    points: [
      'Transcripts are processed entirely on your machine',
      'Nothing is uploaded to a third-party service',
      'Your summaries stay local, on disk',
    ],
  },
  {
    id: 'markdown-export',
    label: 'Markdown Export',
    icon: FileTextIcon,
    headline: 'Download clean, structured study notes.',
    points: [
      'Export summaries and transcripts as Markdown',
      'Timestamps are preserved in the export',
      'Ready for Notion, Obsidian, or any notes app',
    ],
  },
  {
    id: 'timestamp-navigation',
    label: 'Timestamp Navigation',
    icon: ClockIcon,
    headline: 'Jump straight to the moment that matters.',
    points: [
      'Summary sections link to their exact video moment',
      'Click a timestamp to open it in YouTube',
      'Search the transcript to find specific passages',
    ],
  },
]

const QUICK_STEPS = [
  {
    icon: LinkIcon,
    title: 'Paste URL',
    hint: 'Any YouTube URL or Video ID works.',
  },
  {
    icon: FileTextIcon,
    title: 'Fetch transcript',
    hint: 'Automatically fetch the transcript and prepare it for analysis.',
  },
  {
    icon: BrainIcon,
    title: 'Generate AI summary',
    hint: 'Structured study notes with timestamps, generated by your local AI.',
  },
]

function App() {
  const {
    state,
    videoId,
    segments,
    fullText,
    source,
    meta,
    languages,
    selectedLang,
    isLoadingLanguage,
    error,
    load,
    selectLanguage,
    reset,
  } = useTranscript()

  // Feature chips only matter before analysis: fade out once a transcript
  // loads, then drop them from layout; they remount (and fade back in) on reset.
  const [chipsGone, setChipsGone] = useState(false)
  const [activeFeature, setActiveFeature] = useState<string | null>(null)

  useEffect(() => {
    if (state === 'success') {
      const timer = setTimeout(() => setChipsGone(true), 220)
      return () => clearTimeout(timer)
    }
    setChipsGone(false)
  }, [state])

  // Escape closes the open feature panel (unless the user is typing).
  useEffect(() => {
    if (activeFeature === null) return
    function handleKey(event: KeyboardEvent) {
      const target = event.target as HTMLElement
      const isTyping = /^(INPUT|TEXTAREA|SELECT)$/.test(target.tagName)
      if (event.key === 'Escape' && !isTyping) setActiveFeature(null)
    }
    document.addEventListener('keydown', handleKey)
    return () => document.removeEventListener('keydown', handleKey)
  }, [activeFeature])

  const openFeature = FEATURES.find((feature) => feature.id === activeFeature)

  function toggleFeature(id: string) {
    setActiveFeature((current) => (current === id ? null : id))
  }

  return (
    <main className="app">
      <a className="skip-link" href="#content">
        Skip to content
      </a>

      <header className="app-header">
        <h1 className="reveal">
          <YoutubeIcon size={26} />
          <span>
            YouTube Analysis <span className="accent">Pipeline</span>
          </span>
        </h1>
        <p className="tagline reveal" style={{ animationDelay: '80ms' }}>
          Analyze any YouTube video using local AI. Automatically fetch transcripts, generate structured
          summaries, and study videos with intelligent timestamp navigation.
        </p>
      </header>

      <div className="hero-actions reveal" style={{ animationDelay: '160ms' }}>
        <UrlInput onSubmit={load} disabled={state === 'loading'} />

        {!chipsGone && (
          <div className={`feature-chips${state === 'success' ? ' is-fading' : ''}`}>
            {FEATURES.map((feature) => {
              const isActive = activeFeature === feature.id
              return (
                <button
                  type="button"
                  className={`chip${isActive ? ' is-active' : ''}`}
                  key={feature.id}
                  aria-expanded={isActive}
                  aria-controls="feature-panel"
                  onClick={() => toggleFeature(feature.id)}
                >
                  <CheckIcon size={12} />
                  {feature.label}
                </button>
              )
            })}

            <FeaturePanel feature={openFeature ?? null} />
          </div>
        )}
      </div>

      <div id="content">
        {state === 'loading' && <Skeleton />}

        {state === 'error' && (
          <div className="error" role="alert">
            <p>{error}</p>
            <button type="button" className="ghost-btn" onClick={reset}>
              Try again
            </button>
          </div>
        )}

        {state === 'success' && videoId && meta && (
          <TranscriptView
            videoId={videoId}
            meta={meta}
            source={source}
            segments={segments}
            fullText={fullText}
            languages={languages}
            selectedLang={selectedLang}
            isLoadingLanguage={isLoadingLanguage}
            onSelectLanguage={selectLanguage}
            onReset={reset}
          />
        )}

        {state === 'idle' && (
          <div className="quick-start reveal" style={{ animationDelay: '320ms' }}>
            <ol className="quick-steps">
              {QUICK_STEPS.map(({ icon: Icon, title, hint }) => (
                <li key={title}>
                  <span className="quick-step-icon" aria-hidden="true">
                    <Icon size={18} />
                  </span>
                  <div className="quick-step-text">
                    <strong>{title}</strong>
                    <span>{hint}</span>
                  </div>
                </li>
              ))}
            </ol>
          </div>
        )}
      </div>

      <footer className="app-footer reveal" style={{ animationDelay: '400ms' }}>
        Developed by{' '}
        <a href="https://github.com/shreyasgws" target="_blank" rel="noopener noreferrer">
          ShreyasGWS
        </a>
      </footer>
    </main>
  )
}

export default App
